
package dbguijava;
import java.sql.Connection;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

public class QueryPanel extends javax.swing.JFrame {
    Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    /**
     * Creates new form QueryPanel
     */
    public QueryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_mealplan_window = new javax.swing.JFrame();
        week_add_list = new javax.swing.JComboBox<>();
        week_copy_list = new javax.swing.JComboBox<>();
        d1_b_list = new javax.swing.JComboBox<>();
        d1_l_list = new javax.swing.JComboBox<>();
        d1_d_list = new javax.swing.JComboBox<>();
        d2_b_list = new javax.swing.JComboBox<>();
        d2_l_list = new javax.swing.JComboBox<>();
        d2_d_list = new javax.swing.JComboBox<>();
        d3_b_list = new javax.swing.JComboBox<>();
        d3_l_list = new javax.swing.JComboBox<>();
        d3_d_list = new javax.swing.JComboBox<>();
        d4_b_list = new javax.swing.JComboBox<>();
        d4_l_list = new javax.swing.JComboBox<>();
        d4_d_list = new javax.swing.JComboBox<>();
        d5_b_list = new javax.swing.JComboBox<>();
        d5_l_list = new javax.swing.JComboBox<>();
        d5_d_list = new javax.swing.JComboBox<>();
        d6_b_list = new javax.swing.JComboBox<>();
        d6_l_list = new javax.swing.JComboBox<>();
        d6_d_list = new javax.swing.JComboBox<>();
        d7_b_list = new javax.swing.JComboBox<>();
        d7_l_list = new javax.swing.JComboBox<>();
        d7_d_list = new javax.swing.JComboBox<>();
        week_add_label = new javax.swing.JLabel();
        week_copy_label = new javax.swing.JLabel();
        breakfast_label = new javax.swing.JLabel();
        lunch_label = new javax.swing.JLabel();
        add_meal_button = new javax.swing.JButton();
        add_dinner_label = new javax.swing.JLabel();
        day1_label = new javax.swing.JLabel();
        day2_label = new javax.swing.JLabel();
        day3_label = new javax.swing.JLabel();
        day4_label = new javax.swing.JLabel();
        day5_label = new javax.swing.JLabel();
        day6_label = new javax.swing.JLabel();
        day7_label = new javax.swing.JLabel();
        meal_shop_list_frame = new javax.swing.JFrame();
        meal_shop_list = new javax.swing.JList<>();
        search_ing_button = new javax.swing.JButton();
        search_ing_text = new javax.swing.JTextField();
        search_rec_text = new javax.swing.JTextField();
        add_ing_button = new javax.swing.JButton();
        search_rec_button = new javax.swing.JButton();
        table_pane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ing_name_text = new javax.swing.JTextField();
        ing_cat_text = new javax.swing.JTextField();
        ing_nut_text = new javax.swing.JTextField();
        ing_name_label = new javax.swing.JLabel();
        ing_cat_label = new javax.swing.JLabel();
        ing_nut_label = new javax.swing.JLabel();
        rec_name_text = new javax.swing.JTextField();
        rec_cat_text = new javax.swing.JTextField();
        rec_name_label = new javax.swing.JLabel();
        add_rec_button = new javax.swing.JButton();
        rec_ins_text = new javax.swing.JTextField();
        rec_cat_label = new javax.swing.JLabel();
        rec_ins_label = new javax.swing.JLabel();
        shop_list_button = new javax.swing.JButton();
        add_meal_window_button = new javax.swing.JButton();
        show_meal_button = new javax.swing.JButton();
        ing_pane = new javax.swing.JScrollPane();
        rec_ing_list = new javax.swing.JList<>();
        rec_ing_label = new javax.swing.JLabel();

        week_add_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        week_copy_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d1_b_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d1_l_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d1_d_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d2_b_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d2_l_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d2_d_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d3_b_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d3_l_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d3_d_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d4_b_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d4_l_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d4_d_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d5_b_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d5_l_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d5_d_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d6_b_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d6_l_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d6_d_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d7_b_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d7_l_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        d7_d_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        week_add_label.setText("Week To Add");

        week_copy_label.setText("Week To Copy");

        breakfast_label.setText("Breakfast");

        lunch_label.setText("Lunch");

        add_meal_button.setText("Add Meal Plan");

        add_dinner_label.setText("Dinner");

        day1_label.setText("Day 1");

        day2_label.setText("Day 2");

        day3_label.setText("Day 3");

        day4_label.setText("Day 4");

        day5_label.setText("Day 5");

        day6_label.setText("Day 6");

        day7_label.setText("Day 7");

        javax.swing.GroupLayout add_mealplan_windowLayout = new javax.swing.GroupLayout(add_mealplan_window.getContentPane());
        add_mealplan_window.getContentPane().setLayout(add_mealplan_windowLayout);
        add_mealplan_windowLayout.setHorizontalGroup(
            add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_mealplan_windowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day1_label)
                    .addComponent(day2_label)
                    .addComponent(day3_label)
                    .addComponent(day4_label)
                    .addComponent(day5_label)
                    .addComponent(day6_label)
                    .addComponent(day7_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_mealplan_windowLayout.createSequentialGroup()
                        .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(week_copy_label)
                            .addComponent(week_add_label)
                            .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(week_copy_list, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(week_add_list, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_mealplan_windowLayout.createSequentialGroup()
                        .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(add_mealplan_windowLayout.createSequentialGroup()
                                .addComponent(d6_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(d6_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(d6_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(add_mealplan_windowLayout.createSequentialGroup()
                                    .addComponent(d5_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(d5_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(d5_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(add_mealplan_windowLayout.createSequentialGroup()
                                        .addComponent(d4_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(d4_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(d4_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(add_mealplan_windowLayout.createSequentialGroup()
                                            .addComponent(d3_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(d3_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(d3_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(add_mealplan_windowLayout.createSequentialGroup()
                                            .addComponent(d2_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(d2_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(d2_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(add_mealplan_windowLayout.createSequentialGroup()
                                            .addComponent(d1_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(d1_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(d1_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(add_mealplan_windowLayout.createSequentialGroup()
                                .addComponent(d7_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(d7_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(d7_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(add_mealplan_windowLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(breakfast_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lunch_label)
                        .addGap(145, 145, 145)
                        .addComponent(add_dinner_label)
                        .addGap(124, 124, 124))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_mealplan_windowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_meal_button)
                .addGap(264, 264, 264))
        );
        add_mealplan_windowLayout.setVerticalGroup(
            add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_mealplan_windowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(week_add_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(week_add_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(week_copy_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(week_copy_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakfast_label)
                    .addComponent(lunch_label)
                    .addComponent(add_dinner_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d1_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day1_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d2_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day2_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d3_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day3_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d4_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d4_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d4_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day4_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d5_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d5_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d5_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day5_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d6_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d6_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d6_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day6_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(add_mealplan_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d7_b_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d7_l_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d7_d_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day7_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(add_meal_button)
                .addGap(26, 26, 26))
        );

        meal_shop_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        javax.swing.GroupLayout meal_shop_list_frameLayout = new javax.swing.GroupLayout(meal_shop_list_frame.getContentPane());
        meal_shop_list_frame.getContentPane().setLayout(meal_shop_list_frameLayout);
        meal_shop_list_frameLayout.setHorizontalGroup(
            meal_shop_list_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meal_shop_list_frameLayout.createSequentialGroup()
                .addComponent(meal_shop_list, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        meal_shop_list_frameLayout.setVerticalGroup(
            meal_shop_list_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meal_shop_list_frameLayout.createSequentialGroup()
                .addComponent(meal_shop_list, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("main_menu"); // NOI18N

        search_ing_button.setText("Search Ingredients");
        search_ing_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_ing_buttonActionPerformed(evt);
            }
        });

        search_ing_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_ing_textActionPerformed(evt);
            }
        });

        add_ing_button.setText("Add Ingredient");
        add_ing_button.setActionCommand("");
        add_ing_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ing_buttonActionPerformed(evt);
            }
        });

        search_rec_button.setText("Search Recipes");
        search_rec_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_rec_buttonActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_pane.setViewportView(table);

        ing_name_label.setText("Ingredient Name");

        ing_cat_label.setText("Ingredient Category");

        ing_nut_label.setText("Nutritional Facts");

        rec_name_label.setText("Recipe Name");

        add_rec_button.setText("Add Recipe");
        add_rec_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_rec_buttonActionPerformed(evt);
            }
        });

        rec_cat_label.setText("Recipe Category");

        rec_ins_label.setText("Recipe Instructions");

        shop_list_button.setText("Shopping List");
        shop_list_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop_list_buttonActionPerformed(evt);
            }
        });

        add_meal_window_button.setText("Add Meal Plan");
        add_meal_window_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_meal_window_buttonActionPerformed(evt);
            }
        });

        show_meal_button.setText("Show Meal Plan");
        show_meal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_meal_buttonActionPerformed(evt);
            }
        });

        rec_ing_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ing_pane.setViewportView(rec_ing_list);

        rec_ing_label.setText("Ingredients");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(search_rec_button)
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ing_nut_text)
                                    .addComponent(ing_cat_text)
                                    .addComponent(ing_name_text)
                                    .addComponent(search_ing_text)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 31, Short.MAX_VALUE)
                                        .addComponent(search_ing_button)
                                        .addGap(37, 37, 37))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ing_name_label)
                                            .addComponent(ing_cat_label)
                                            .addComponent(ing_nut_label)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(show_meal_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(shop_list_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(add_meal_window_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(add_ing_button))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(search_rec_text, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(rec_cat_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rec_name_label, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rec_cat_label, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addComponent(rec_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(rec_ing_label)))
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rec_ins_text, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rec_ins_label))
                                            .addComponent(ing_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_rec_button, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addComponent(table_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(table_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(ing_name_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ing_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ing_cat_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ing_cat_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ing_nut_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ing_nut_text, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_ing_button)
                        .addGap(52, 52, 52)
                        .addComponent(add_meal_window_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(show_meal_button)
                        .addGap(7, 7, 7)
                        .addComponent(shop_list_button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_rec_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_ing_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_rec_button)
                            .addComponent(search_ing_button))
                        .addGap(18, 18, 18)
                        .addComponent(rec_name_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rec_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rec_cat_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rec_cat_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rec_ing_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ing_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rec_ins_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rec_ins_text, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add_rec_button)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_ing_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_ing_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_ing_buttonActionPerformed

    private void search_ing_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_ing_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_ing_textActionPerformed

    private void add_ing_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ing_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_ing_buttonActionPerformed

    private void search_rec_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_rec_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_rec_buttonActionPerformed

    private void add_rec_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_rec_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_rec_buttonActionPerformed

    private void shop_list_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shop_list_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shop_list_buttonActionPerformed

    private void add_meal_window_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_meal_window_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_meal_window_buttonActionPerformed

    private void show_meal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_meal_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_meal_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueryPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_dinner_label;
    private javax.swing.JButton add_ing_button;
    private javax.swing.JButton add_meal_button;
    private javax.swing.JButton add_meal_window_button;
    private javax.swing.JFrame add_mealplan_window;
    private javax.swing.JButton add_rec_button;
    private javax.swing.JLabel breakfast_label;
    private javax.swing.JComboBox<String> d1_b_list;
    private javax.swing.JComboBox<String> d1_d_list;
    private javax.swing.JComboBox<String> d1_l_list;
    private javax.swing.JComboBox<String> d2_b_list;
    private javax.swing.JComboBox<String> d2_d_list;
    private javax.swing.JComboBox<String> d2_l_list;
    private javax.swing.JComboBox<String> d3_b_list;
    private javax.swing.JComboBox<String> d3_d_list;
    private javax.swing.JComboBox<String> d3_l_list;
    private javax.swing.JComboBox<String> d4_b_list;
    private javax.swing.JComboBox<String> d4_d_list;
    private javax.swing.JComboBox<String> d4_l_list;
    private javax.swing.JComboBox<String> d5_b_list;
    private javax.swing.JComboBox<String> d5_d_list;
    private javax.swing.JComboBox<String> d5_l_list;
    private javax.swing.JComboBox<String> d6_b_list;
    private javax.swing.JComboBox<String> d6_d_list;
    private javax.swing.JComboBox<String> d6_l_list;
    private javax.swing.JComboBox<String> d7_b_list;
    private javax.swing.JComboBox<String> d7_d_list;
    private javax.swing.JComboBox<String> d7_l_list;
    private javax.swing.JLabel day1_label;
    private javax.swing.JLabel day2_label;
    private javax.swing.JLabel day3_label;
    private javax.swing.JLabel day4_label;
    private javax.swing.JLabel day5_label;
    private javax.swing.JLabel day6_label;
    private javax.swing.JLabel day7_label;
    private javax.swing.JLabel ing_cat_label;
    private javax.swing.JTextField ing_cat_text;
    private javax.swing.JLabel ing_name_label;
    private javax.swing.JTextField ing_name_text;
    private javax.swing.JLabel ing_nut_label;
    private javax.swing.JTextField ing_nut_text;
    private javax.swing.JScrollPane ing_pane;
    private javax.swing.JLabel lunch_label;
    private javax.swing.JList<String> meal_shop_list;
    private javax.swing.JFrame meal_shop_list_frame;
    private javax.swing.JLabel rec_cat_label;
    private javax.swing.JTextField rec_cat_text;
    private javax.swing.JLabel rec_ing_label;
    private javax.swing.JList<String> rec_ing_list;
    private javax.swing.JLabel rec_ins_label;
    private javax.swing.JTextField rec_ins_text;
    private javax.swing.JLabel rec_name_label;
    private javax.swing.JTextField rec_name_text;
    private javax.swing.JButton search_ing_button;
    private javax.swing.JTextField search_ing_text;
    private javax.swing.JButton search_rec_button;
    private javax.swing.JTextField search_rec_text;
    private javax.swing.JButton shop_list_button;
    private javax.swing.JButton show_meal_button;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane table_pane;
    private javax.swing.JLabel week_add_label;
    private javax.swing.JComboBox<String> week_add_list;
    private javax.swing.JLabel week_copy_label;
    private javax.swing.JComboBox<String> week_copy_list;
    // End of variables declaration//GEN-END:variables
}
